"""User info table

Revision ID: d9c6ef779bb9
Revises: edb8d3b1ad4e
Create Date: 2024-06-04 14:40:54.618009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c6ef779bb9'
down_revision: Union[str, None] = 'edb8d3b1ad4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_infos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_infos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_infos', type_='foreignkey')
    op.drop_column('user_infos', 'user_id')
    # ### end Alembic commands ###
