"""email field type fixed in User

Revision ID: edb8d3b1ad4e
Revises: cf8ca5f0681e
Create Date: 2024-06-03 16:14:30.000864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb8d3b1ad4e'
down_revision: Union[str, None] = 'cf8ca5f0681e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
